services:
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env #General settings
      - .env.secret  #Sensitive settings, not tracked in git
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata-1:/var/lib/postgresql/data

volumes:
  pgdata-1: 